rushia: slash: svrinfo: don't define langc, use provided         const langc = await db.get(`${interaction.guild.id}_lang`);               ^
SyntaxError: Identifier 'langc' has already been declared
    at Object.compileFunction (node:vm:360:18)
    at wrapSafe (node:internal/modules/cjs/loader:1055:15)
    at Module._compile (node:internal/modules/cjs/loader:1090:27)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1180:10)
    at Module.load (node:internal/modules/cjs/loader:1004:32)
    at Function.Module._load (node:internal/modules/cjs/loader:839:12)
    at Module.require (node:internal/modules/cjs/loader:1028:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at C:\Users\A\OneDrive\Desktop\git\rushia\structures\slash.js:11:24
    at Array.forEach (<anonymous>)