rushia: Commands: info: member-update: seperate record for nickname and username * use local variables before pushing to database * also check saved record instead of oldMember.roles.cache * wait for 1 second for new record incase recorded was null
* fixes
[ERROR] Unhandled promise rejection: UNIQUE constraint failed: json.ID.
SqliteError: UNIQUE constraint failed: json.ID
    at SqliteDriver.setRowByKey (/run/media/alecchangod/Data/git/rushia/node_modules/quick.db/out/drivers/SqliteDriver.js:50:18)
    at QuickDB.set (/run/media/alecchangod/Data/git/rushia/node_modules/quick.db/out/index.js:114:28)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Object.run (/run/media/alecchangod/Data/git/rushia/Commands/info/member-update.js:110:9) {
  code: 'SQLITE_CONSTRAINT_PRIMARYKEY'
}